### ISSUE TITLE
Reduce MathJax size

### ISSUE THREAD

**Issue by Integral** [substance/tahi-editor-ve#2]
Hey @oliver---- 

Did some investigations on MathJax size topic.
It seems that most size of library came from image fonts. They have around 30k of images for old browsers which are not compatible with font-face.

So we could change config and remove those thousands of images. Other fonts most remain untouchable.
Official documentation says that IE6+, Chrome, Safari 3.1+, Firefox 3.5+, and Opera 10+, or other browsers based on their rendering engines will work. On earlier browsers (without local fonts) or if webfonts are blocked , MathJax will not be able to render math reliably (though it will try its best). Also it will work with oldif you have the MathJax or STIX fonts.

Don't know project requirements, but I feel that we could remove images, yeah?

**Comment by oliver----** [comment]
I think, we do not really care about old browsers, as the editor does not.
So, yes, remove them.

**Comment by Integral** [comment]
will do, what are our plans?
